settings:
  radius: 15.0
  punishment: "INSTANT_KILL"
  damage-interval: 20

game-loop:
  min-players: 2
  class-selection-time: 15

random-objective:
  blacklist:
    - BEDROCK
    - BARRIER
    - COMMAND_BLOCK
    - END_PORTAL_FRAME
    - STRUCTURE_VOID
    - LIGHT
    - SPAWNER
    - DRAGON_EGG
    - REINFORCED_DEEPSLATE
