name: EscoltaCore
version: '${project.version}'
main: com.escoltacore.EscoltaCorePlugin
api-version: '1.21'
authors: [ _gengis ]
description: Escort arcade minigame. Original concept by ElRichMC.
softdepend: [ PlaceholderAPI ]

commands:
  escolta:
    description: EscoltaCore main command
    usage: /escolta <admin|user>

permissions:
  escoltacore.admin:
    description: Full admin access to EscoltaCore
    default: op
  escoltacore.play:
    description: Access to player commands
    default: true
