name: EscoltaCore
version: '1.0-SNAPSHOT'
main: com.escoltacore.EscoltaCorePlugin
api-version: '1.21'
authors: [ _gengis ]
description: Un minijuego Arcade. Concepto original de ElRichMC - Modo Escolta.
softdepend: [PlaceholderAPI]

commands:
  escolta:
    description: Comandos principales del juego
    permission: escoltacore.admin
    usage: /escolta <create|join|leave|start|config|reload>

permissions:
  escoltacore.admin:
    description: Acceso a todos los comandos de EscoltaCore
    default: op
